In [1]:
import pandas as pd

C:\Users\Prathmesh\AppData\Roaming\Python\Python311\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
import numpy as np

In [3]:
data = pd.read_csv('customer.csv')
data

    age  gender   review education purchased
0    30  Female  Average    School        No
1    68  Female     Poor        UG        No
2    70  Female     Good        PG        No
3    72  Female     Good        PG        No
4    16  Female  Average        UG        No
5    31  Female  Average    School       Yes
6    18    Male     Good    School        No
7    60  Female     Poor    School       Yes
8    65  Female  Average        UG        No
9    74    Male     Good        UG       Yes
10   98  Female     Good        UG       Yes
11   74    Male     Good        UG       Yes
12   51    Male     Poor    School        No
13   57  Female  Average    School        No
14   15    Male     Poor        PG       Yes
15   75    Male     Poor        UG        No
16   59    Male     Poor        UG       Yes
17   22  Female     Poor        UG       Yes
18   19    Male     Good    School        No
19   97    Male     Poor        PG       Yes
20   57  Female  Average    School       Yes
21   32    Male  Average        PG        No
22   18  Female     Poor        PG       Yes
23   96  Female     Good    School        No
24   16  Female  Average        PG       Yes
25   57  Female     Good    School        No
26   53  Female     Poor        PG        No
27   69  Female     Poor        PG        No
28   48    Male     Poor    School        No
29   83  Female  Average        UG       Yes
30   73    Male  Average        UG        No
31   22  Female     Poor    School       Yes
32   92    Male  Average        UG       Yes
33   89  Female     Good        PG       Yes
34   86    Male  Average    School        No
35   74    Male     Poor    School       Yes
36   34  Female     Good        UG       Yes
37   94    Male  Average        PG       Yes
38   45  Female     Good    School        No
39   76    Male     Poor        PG        No
40   39    Male     Good    School        No
41   23    Male     Good        PG       Yes
42   30  Female     Good        PG       Yes
43   27    Male     Poor        PG        No
44   77  Female  Average        UG        No
45   61    Male     Poor        PG       Yes
46   64  Female     Poor        PG        No
47   38  Female     Good        PG       Yes
48   39  Female     Good        UG       Yes
49   25  Female     Good        UG        No

In [4]:
data = data.iloc[:,2:]

In [5]:
data

     review education purchased
0   Average    School        No
1      Poor        UG        No
2      Good        PG        No
3      Good        PG        No
4   Average        UG        No
5   Average    School       Yes
6      Good    School        No
7      Poor    School       Yes
8   Average        UG        No
9      Good        UG       Yes
10     Good        UG       Yes
11     Good        UG       Yes
12     Poor    School        No
13  Average    School        No
14     Poor        PG       Yes
15     Poor        UG        No
16     Poor        UG       Yes
17     Poor        UG       Yes
18     Good    School        No
19     Poor        PG       Yes
20  Average    School       Yes
21  Average        PG        No
22     Poor        PG       Yes
23     Good    School        No
24  Average        PG       Yes
25     Good    School        No
26     Poor        PG        No
27     Poor        PG        No
28     Poor    School        No
29  Average        UG       Yes
30  Average        UG        No
31     Poor    School       Yes
32  Average        UG       Yes
33     Good        PG       Yes
34  Average    School        No
35     Poor    School       Yes
36     Good        UG       Yes
37  Average        PG       Yes
38     Good    School        No
39     Poor        PG        No
40     Good    School        No
41     Good        PG       Yes
42     Good        PG       Yes
43     Poor        PG        No
44  Average        UG        No
45     Poor        PG       Yes
46     Poor        PG        No
47     Good        PG       Yes
48     Good        UG       Yes
49     Good        UG        No

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X = data[['review','education']]
y = data['purchased']

In [8]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)
#X_trainq,X_testq,y_trainq,y_testq = train_test_split(data.iloc[:,0:2],data.iloc[:,-1],test_size=0.2,random_state=0)

In [9]:
X_train

     review education
33     Good        PG
35     Poor    School
26     Poor        PG
34  Average    School
18     Good    School
7      Poor    School
14     Poor        PG
45     Poor        PG
48     Good        UG
29  Average        UG
15     Poor        UG
30  Average        UG
32  Average        UG
16     Poor        UG
42     Good        PG
20  Average    School
43     Poor        PG
8   Average        UG
13  Average    School
25     Good    School
5   Average    School
17     Poor        UG
40     Good    School
49     Good        UG
1      Poor        UG
12     Poor    School
37  Average        PG
24  Average        PG
6      Good    School
23     Good    School
36     Good        UG
21  Average        PG
19     Poor        PG
9      Good        UG
39     Poor        PG
46     Poor        PG
3      Good        PG
0   Average    School
47     Good        PG
44  Average        UG

In [10]:
y_train

   purchased
33       Yes
35       Yes
26        No
34        No
18        No
7        Yes
14       Yes
45       Yes
48       Yes
29       Yes
15        No
30        No
32       Yes
16       Yes
42       Yes
20       Yes
43        No
8         No
13        No
25        No
5        Yes
17       Yes
40        No
49        No
1         No
12        No
37       Yes
24       Yes
6         No
23        No
36       Yes
21        No
19       Yes
9        Yes
39        No
46        No
3         No
0         No
47       Yes
44        No

In [11]:
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder

In [12]:
ordinal = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [13]:
ordinal.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [14]:
X_train=ordinal.transform(X_train)
X_test=ordinal.transform(X_test)

In [15]:
X_train

array([[2., 2.],
       [0., 0.],
       [0., 2.],
       [1., 0.],
       [2., 0.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [0., 1.],
       [0., 0.],
       [1., 2.],
       [1., 2.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [1., 2.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [2., 2.],
       [1., 1.]])

In [16]:
ordinal.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [17]:
le = LabelEncoder()

In [18]:
le.fit(y_train)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:97: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LabelEncoder()

In [19]:
y_train=le.transform(y_train)
y_test = le.transform(y_test)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

In [20]:
y_train

array([1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0])

In [21]:
le.classes_

array(['No', 'Yes'], dtype=object)